### PR TITLE
0.62.0

### PR DESCRIPTION
**Pull request by internetbird**
New contributer

### CODE REVIEW

**Comment by coni2k** [comment]
internetbird hi,

Thank you for sending a pull request for contributors page.
Your change looks good, however you have sent the PR to "master" branch.
Could you please resend it by choosing "puslish" branch?

**Comment by internetbird** [comment]
Yes, of course :) Thanks

**Comment by internetbird** [comment]
I try to make a new pull request to the publish branch but this is what I get:

image

It seems that the publish branch is up to date with my master branch...

**Comment by coni2k** [comment]
Interesting, there are actually differences but maybe somehow I had caused it.
I reversed my changes, could you try it again?

You're sending the pull request through Github right? Like in the tutorial (Step 6/6):
https://github.com/forCrowd/WealthEconomy/wiki/First-Mission

**Comment by coni2k** [comment]
I believe you pushed one more time after my last message.
I got it but was still pointing to master, so still couldn't apply them.

Since this pull request is closed now, I believe if you could try it again, but just pointing to "forCrowd:publish" branch, it should be okay.

Let me know if you have any issues?

**Pull request merged**
