### PR TITLE
0.62.0

### PR DESCRIPTION
**Pull request by internetbird**

### CODE REVIEW

**Comment by coni2k** [comment]
Shai hi,

Thanks for the PR. Merged and published :)
https://wealth.forcrowd.org/_system/content/contributors

If you would like to update your info later on, feel free to send me a new request.

Hope it was easy to setup and instructions were clear btw? Let me know if you had any issues.

Also, if you would like to work on our project, you are more than welcome, again just let me know.

**Comment by internetbird** [comment]
Thanks @coni2k ! I would be happy to contribute to this project.
Do you have any road map of features you plan to be working on? Are you open for any suggestions for improvments?

**Comment by coni2k** [comment]
Yes, I am definitely open for suggestions, please send me if you have any ideas.

There is no proper to do list at the moment but I'm planning to work on it.
Today and tomorrow I will be on the way, so I can answer bit late. And afterwards we can talk about what we can do.

**Comment by coni2k** [comment]
Shai hello again,

Sorry for my late reply, lately it was pretty busy here.

Here is a quick list of ideas for the project.

* angular2 / asp.net core: Last update was about typescript. Now I would like to study these two technologies a little bit. If it's easy to switch, I'll try to upgrade the application.
* New UI / content: Current UI is not good as I want. It should be easier to use and understand. Probably I will move current extensive content into medium articles and try to have admin dashboard kind of UI for the application.
* Embeddable: What I would like to create is some sort of survey application and I would like to experiment with making it embeddable to other websites. Since I'm planning to use medium for the content part, it should be embeddable to medium for instance. So, inside of your article, you can ask some questions and make your article bit more interactive.
* Custom formulas: Current application has some field types and based on these types, it creates cells with a fixed formula. On top of this, I'd like to introduce custom formulas, at least basic operations (addition, subtraction, sum, average etc.) Make the application more excel-like, so you can create your own field with custom formulas.

And of course there are lot of small items to work on as well.

If you find any of it interesting, just let me know and we can look how we can work together. As you can see, I'm learning through this process as well. So, again, if you have any ideas, please feel free to share.

**Pull request merged**
