### PR TITLE
My first pull request

### PR DESCRIPTION
**Pull request by shilpavijay**
Thanks for this. Helps me learn.

### CODE REVIEW

**Comment by coni2k** [comment]
Shilpa hi,
Thanks for the PR, however you also closed it, are you going to send a new one, or should I merge this (which looks good)?

**Comment by shilpavijay** [comment]
The same can be merged if it is fine. Thanks.

**Comment by coni2k** [comment]
Shilpa hi again,

Thanks for the PR, it's merged and published :)
https://wealth.forcrowd.org/_system/content/contributors

If you would like to update your info later on, feel free to send me a new request.

Hope it was easy to setup the project and instructions were clear?
Let me know if you had any issues.

And if you would like to get updates about the project, you can follow us on twitter
https://twitter.com/forCrowd

**Comment by shilpavijay** [comment]
The instructions were quite elaborate and clear. Was easy to follow. Thanks for the twitter link.

**Pull request merged**
