### PR TITLE
0.82.4 - chrised123

### PR DESCRIPTION
**Pull request by chrised123**
Added **Chrised123**'s details to the contributor page.

### CODE REVIEW

**Comment by coni2k** [comment]
Hi Sanjith,

Thank you for sending a PR, I just merged and published it! 👍
https://wealth.forcrowd.org/app/contributors

If you would like to update your info later on, feel free to send me a new request.

Let me know if you had any issues, and/or whether the instructions were clear.

And if you would like to get updates about our projects, you can follow us on twitter:
https://twitter.com/forCrowd

**Comment by chrised123** [comment]
I would like to contribute to the project. Is that possible?

**Comment by coni2k** [comment]
Of course, that would be great.

Recently I created another project based on Wealth, to make the back-end more generic, so I can quickly develop prototypes for other ideas:
https://github.com/forCrowd/Backbone

Structure is the same, I made it bit simpler and started using Angular Material for front-end. Please clone this one and check how it works/looks. The idea is that when you create a new project (database), we should be able to use this database from any other front-end application. My plans is create basic survey / timelime / voting etc. type of applications on top of it.

How much time can you spend on this project, and do you have any preference, back-end, front-end, unit tests etc?

**Comment by chrised123** [comment]
I am mainly into front-end. But, I can do some .net work as well because I am working on the same stack.
I can contribute 4 hrs a week.

**Comment by coni2k** [comment]
@chrised123 great! I just created this issue for Backbone project:
https://github.com/forCrowd/Backbone/issues/1

Would you pick this one up?

**Pull request merged**
