### PR TITLE
Version 0.62.0

### PR DESCRIPTION
**Pull request by johndsykes86**

### CODE REVIEW

**Comment by coni2k** [comment]
Johnathon hi,
Thank you for your interest in our project.

I believe you tried to complete our "Contributors page" step.
However, in your PR, there is no change in the files. Did you encounter any issues?

**Comment by johndsykes86** [comment]
Ill check locally but it looked like it picked up the changes to the
markdown and html pages

**Comment by johndsykes86** [comment]
Ok, fixed....

It seems that I forgot to sync before doing the pull request.

**Comment by coni2k** [comment]
Great, looks good now.
I will look at it in detail in the morning.

**Comment by coni2k** [comment]
Okay, this was fine. Merged & published :)
https://wealth.forcrowd.org/_system/content/contributors

And in case if you would like to update your info, you can send me a new pull request.

**Comment by coni2k** [comment]
Hope the setup was easy and instructions were clear btw? Let me know if you had any issues.

Also, if you would like to work on our project, you are welcome. If you wish, I can try to find suitable items for you?

**Comment by johndsykes86** [comment]
I would love to work on the project some more.

**Comment by coni2k** [comment]
Okay, great.

One of items that we could work on is to copy search functionality from Search to Profile page.

Search page:
https://wealth.forcrowd.org/_system/resourcePool/search

One of the user's profile page
https://wealth.forcrowd.org/sample

Search related files:
ngClient\_system\views\resourcePool\resourcePoolSearch.html
ngClient\_system\js\app\controllers\resourcePool\ResourcePoolSearchController.js

Profile related files:
ngClient\_system\views\account\profile.html
ngClient\_system\js\app\controllers\account\ProfileController.js

If you wish, check this one and let me know whether its something you can do.

**Pull request merged**
