### PR TITLE
0.64.0

### PR DESCRIPTION
**Pull request by carolineh101**

### CODE REVIEW

**Comment by coni2k** [comment]
Caroline hi,

Thanks for the PR. Merged and published :)
https://wealth.forcrowd.org/_system/content/contributors

If you would like to update your info later on, feel free to send me a new request.

Hope it was easy to setup and instructions were clear btw? Let me know if you had any issues.

Also, if you would like to work on our project, you are more than welcome, again just let me know.

**Comment by coni2k** [comment]
And if you would like to get updated about the project, you can follow us on twitter
https://twitter.com/forCrowd

**Comment by carolineh101** [comment]
Thank you! Setup and instructions were clear and easy to follow. I'm a beginner in open source and frontend web development, but I'd be interested in helping out in small ways if I can!

**Comment by coni2k** [comment]
Good to hear that it was clear.
And if I can find something easy, I can let you know. Thank you again :)

**Pull request merged**
