### PR TITLE
0.64.0 Add Robert Axelsen as contributor

### PR DESCRIPTION
**Pull request by robeerob**

### CODE REVIEW

**Comment by coni2k** [comment]
Robert hi,

Thanks for the PR, it's merged and published :)
https://wealth.forcrowd.org/_system/content/contributors

If you would like to update your info later on, feel free to send me a new request.

Hope it was easy to setup the project and instructions were clear? Let me know if you had any issues.

And if you would like to get updates about the project, you can follow us on twitter
https://twitter.com/forCrowd

**Comment by robeerob** [comment]
Hi :) Was great to be part of this, and experience a pull request.

I had some issues as I am using Linux, but managed to use your guide together with some git cli knowledge and googling. Used vim, git cli and pull request via github.com on my forked repo.

**Comment by coni2k** [comment]
Sounds great! If I'm not mistaken, then you're the first person that tried and made it on a Linux, that's good hear :)

Of course the project itself wasn't running on Linux (right?), only editing the html file was possible. Hopefully I will make the necessary upgrade to the project (switching to Asp.Net Core), so that it will fully run on Linux, through local webserver.

At the moment, I don't have any other fixed items. However, if you see something that you can contribute, just let me know and we can look at it together.

**Comment by robeerob** [comment]
Virtual Studio Community Edition was not available for Linux, so I could not do the 7/11) "install node packages" part in the [Getting Started](https://github.com/forCrowd/WealthEconomy/wiki/Getting-Started) guide as described.

I did try just now to install from inside the ngClient dir:
`npm install`

But it returns a "failed to parse json" error message.

**Comment by coni2k** [comment]
Yep, node packages belong .Net environment, so that's normal that you miss this step in Linux, since currently the project is only compatible with Windows OS. Hopefully I will try to do the necessary upgrade soon, then maybe we can try it again.

Having that error message for "npm install" is bit strange, that should simply install "node" packages for the current project. However, my knowledge about Linux environment is limited. So, again, if I can study Linux OS and create a manual for that, then we can try it again.

be normal, since that command only creates "package.json" in the root folder of the project and we already have that file. "npm 

Having that error message for "npm install" is something else however. npm install basically creates package.json in the root of the project.

**Comment by robeerob** [comment]
Thanks for the clarification, coni2k. Linux version would be great. If you can remember to, please keep me in the loop for any Linux development. I might be able to help as I will be getting more and more into Node.js in the the time to come.

**Comment by coni2k** [comment]
Sure, of course, this is good to hear. We could experiment on it together. Thanks again Robert!

**Pull request merged**
