### PR TITLE
0.64.4

### PR DESCRIPTION
**Pull request by megane-vilain**

### CODE REVIEW

**Comment by coni2k** [comment]
Megane hi,

Thanks for the PR, it's merged and published :)
https://wealth.forcrowd.org/_system/content/contributors

If you would like to update your info later on, feel free to send me a new request.

Hope it was easy to setup the project and instructions were clear?
Let me know if you had any issues.

And if you would like to get updates about the project, you can follow us on twitter
https://twitter.com/forCrowd

**Comment by megane-vilain** [comment]
Hi, thanks for your reponse :)
I do have an issue... When i start the project in visual studio, i can't properly view the website generated.
Here a capture of what i get ... I'm not sure of the reason, since i don't get any errors at the lauch...
capture

**Comment by coni2k** [comment]
This is interesting, thanks for letting me know. I am going to look at it in detail tomorrow morning, however, do you check the console of your browser? Are there any errors in the console? Also what is your browser and operating system?

**Comment by megane-vilain** [comment]
I fixed the issue, i needed to install the module any-promise and bluebird in order to successfully run the ngClient.

**Comment by coni2k** [comment]
You're talking about node packages, right? I am pretty new to node as well. As far as I understand, somehow, dependencies of some packages change. No idea yet whether it has something to the with client and/or the author actually update the dependencies and republish the package etc.

In any case, good to know that you solved it, and I will try to ensure that it doesn't happen again.

**Comment by megane-vilain** [comment]
Sorry, yes i was talking about node packages.
It seems that bluebird and any-promise are dependencies of the package Typings
[https://www.npmjs.com/package/typings](url)

**Comment by coni2k** [comment]
Okay, thanks for info and letting me know about how it went with your setup.

In case if you would like to play around more and make some other contributions, just let me know. Currently I'm upgrading ngClient to angular2 (meanwhile "typings" will be gone as well), hopefully it will be ready more or less in a week.

**Comment by megane-vilain** [comment]
I have some knowledge in AngularJs but i never tested the new version. 
If this is okay for you, i would like to help :)

**Comment by coni2k** [comment]
Okay, that's good to hear. As I said, I'm working on this upgrade and hopefully that's finished soon. After that, maybe we can look together what you can be interesting for you to work on?

**Comment by megane-vilain** [comment]
Yes, just contact me when you are done with the upgrade :)

**Pull request merged**
