### PR TITLE
0.61.3

### PR DESCRIPTION
**Pull request by seannam**

### CODE REVIEW

**Comment by seannam** [comment]
I'm on a Mac so while I couldn't run the project (instructions only for Windows), I did manage to find the necessary files to update accordingly.

**Comment by coni2k** [comment]
Sean hi,
Thanks for the PR. Merged and published :)
https://wealth.forcrowd.org/_system/content/contributors

And in case if you would like to update your info later on, you can send me a new pull request.

**Comment by coni2k** [comment]
Hope the setup was easy and instructions were clear btw? Let me know if you had any issues.

Also, if you would like to work on our project, you are welcome. If you wish, I can try to find suitable items for you?

**Comment by seannam** [comment]
I just really wished there were instructions for Mac as I couldn't figure out how to build the project.

The Windows instructions were fairly easy to follow.

I'd love to work on it, if only I could build the project! I'll let you know if I manage to do so. I love the concept behind the first mission.

**Comment by coni2k** [comment]
Okay, good to hear that.

For Mac (OS X), they released Visual Studio Code, I believe compact version of Visual Studio. I never tried it, but if you like you can check it:
https://code.visualstudio.com/download

And if you succeed, maybe we can prepare a tutorial for Mac with this tool?

**Comment by seannam** [comment]
That's actually what I used to open the project files. However, it is not a full IDE, just a feature-rich code editor, as far as I can know. Also, because of the made for windows .sin file and the fact I haven't set up a node base app before, I'm not sure how to proceed.

**Comment by coni2k** [comment]
You're right. Mac environment is quite different for me and not sure what is possible at the moment.
I need to setup a VM and see what is available. If I can make a progress in a short time, I can let you know.

For the rest thanks again. And let me know if you have any other questions.

**Pull request merged**
