### PR TITLE
0.64.0

### PR DESCRIPTION
**Pull request by sandra-dudley**

### CODE REVIEW

**Comment by coni2k** [comment]
Sandra hi,

Thanks for the PR, it's merged and published :)
https://wealth.forcrowd.org/_system/content/contributors

If you would like to update your info later on, feel free to send me a new request.

Hope it was easy to setup the project and instructions were clear?
Let me know if you had any issues.

And if you would like to get updates about the project, you can follow us on twitter
https://twitter.com/forCrowd

**Comment by sandra-dudley** [comment]
Thanks for accepting the PR and for the instructions - they were simple and clear to follow. The only problem I had was installing visual studio - but it has nothing to do with your guide. So thanks again, it gives me a bit more confidence for future PR.

**Comment by coni2k** [comment]
Thanks for the feedback Sandra, this was good to hear.

**Comment by coni2k** [comment]
By the way, when there is a new contributor, I send a tweet by mentioning the new member. If you have a twitter and would like be mentioned, just let me know your handler please.

**Pull request merged**
